### ISSUE TITLE
Cannot pull imgui submodule.

### ISSUE THREAD

**Issue by MrSoup678** [Xrysnow/LuaSTG-x#1]
Submodule imgui uses commit https://github.com/Xrysnow/cocos2d-x-imgui/commit/acf1f5f6c58ca1ddcfb6b1cc9d00048fe2f8ff82 which is detached from branch and therefore git cannot checkout to commit.

**Comment by SirnoChan** [comment]
The same problem met. I am sure not my network...

**Comment by Xrysnow** [comment]
fixed
