### ISSUE TITLE
lstg.GameObjectBentLaser:collisionCheck(object) does not work

### ISSUE THREAD

**Issue by zinoLath** [Xrysnow/LuaSTG-x#6]
When calling lstg.GameObjectBentLaser:collisionCheck() with an object as the parameter, the game crashes, giving this error:
![LuaSTG-x_39btGYFFRl](https://user-images.githubusercontent.com/58287992/149412949-749e3e4e-cf23-4384-95df-e8f868587a07.png)

**Comment by Xrysnow** [comment]
This should be fixed in 69d06bc.
